services:
  vintage-story:
    container_name: vsserver
    env_file:
      - .env
      - .env.custom
    build:
      context: ./
      dockerfile: Dockerfile
    # image: pepecitron/vintagestory-server
    stdin_open: true
    tty: true
    environment:
      - SERVER_PORT=42420
    ports:
      - "42420:42420"
    volumes:
      - ./data:/data/server-file
      - ./mods:/data/server-file/Mods
